name: Execute Common Build Steps

on:
  workflow_call:

jobs:
  common-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew test build

#      - name: Upload build
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ github.sha }}
#          path: |
#            apps/**
#            docker/**
#          retention-days: 7

#      - name: Upload test coverage
#        uses: actions/upload-artifact@v4
#        with:
#          name: test-coverage-${{ github.sha }}
#          path: ./build/reports/jacoco/testCodeCoverageReport
#          retention-days: 7
