name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        required: true
        default: minor
        description: bumps the [major].[minor].[patch] - note patch is reserved for break fixes to a version already deployed to prod. patching must be done manually.
        options:
          - major
          - minor

jobs:
  increment-tag:
    uses: ./.github/workflows/common-tag.yml
    with:
      version: ${{ inputs.version }}
  release:
    runs-on: ubuntu-latest
    needs: increment-tag
    outputs:
      tag: ${{ steps.prerelease.outputs.tag }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git tag | sort -V | tail -n 1)
          LATEST_RELEASE_TAG=$(gh release list --exclude-pre-releases --exclude-drafts | head -n 1 | awk '{print $3}')
          gh release create -p $TAG --generate-notes --notes-start-tag $LATEST_RELEASE_TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy my app
    needs: [release]
    uses: ./.github/workflows/common-deployment.yml
    secrets: inherit

