name: Main - Build & Deploy

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    secrets: inherit

  deploy:
    name: Deploy my app
    needs: build
    uses: ./.github/workflows/common-deployment.yml
    secrets: inherit

  tag:
    # only tag when not pushing a tag
    if: contains(github.ref, 'main')
    needs: deploy
    uses: ./.github/workflows/common-tag.yml
    secrets: inherit
    with:
      version: prerel

