name: Main - Build & Deploy

on:
  push:
    branches:
      - main
    tags:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/common-build.yml
    secrets: inherit

  deploy:
    name: Deploy my app
    needs: build
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://google.com
          environment: QA

      - name: Deploy my app
        run: |
          # add your deployment code here

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
  tag:
    # only tag when not pushing a tag
    if: contains(github.ref, 'main')
    needs: deploy
    uses: ./.github/workflows/common-tag.yml
    secrets: inherit
    with:
      version: prerel

