name: Measure coverage

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'
      - name: Run Coverage
        run: ./gradlew test
#      - name: Add coverage to PR
#        id: jacoco
#        uses: one-thd/jacoco-report@v1.6.2
#        with:
#          paths: |
#            ${{ github.workspace }}/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
#          token: ${{ secrets.GITHUB_TOKEN }}
#          min-coverage-overall: 70
#          min-coverage-changed-files: 80
#          update-comment: true
#          title: jacoco coverage